# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 finevals.ai and contributors.
"""Classify the panel's columns and emit a draft tokenizer config.

Buckets each column into id / time / drop(constant) / profile(static) / event(dynamic),
split by value type. Prints a report and (optionally) writes a YAML scaffold to review.

Run on the TRAIN split so cardinality stats stay train-only:
    python scripts/classify_schema.py --input data/processed/train.parquet \
        --out configs/dutch_mortgages/tokenizer.yaml
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from credit_fm.data.schema import classify_fields

TYPE_GROUP = {"numeric": "numeric", "categorical": "categorical", "flag": "flags",
              "bucket": "buckets"}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", default="data/processed/train.parquet")
    ap.add_argument("--id-col", default="loan_id")
    ap.add_argument("--time-col", default="reporting_date")
    ap.add_argument("--out", default=None, help="write a YAML scaffold to this path")
    args = ap.parse_args()

    src = Path(args.input)
    if not src.exists():
        raise SystemExit(f"{src} not found — run scripts/prepare_data.py first (or pass --input).")
    df = pd.read_parquet(src)
    info = classify_fields(df, id_col=args.id_col, time_col=args.time_col)

    rep = pd.DataFrame(info).T[["role", "type", "n_unique", "null_frac"]]
    print(f"{src}: {len(df):,} rows, {df.shape[1]} cols\n")
    print(rep.to_string())
    print("\nrole:", rep.role.value_counts().to_dict())
    print("type:", rep.type.value_counts().to_dict())

    if not args.out:
        return

    def group(role):
        g: dict[str, list[str]] = {"numeric": [], "categorical": [], "flags": [], "buckets": []}
        for c, d in info.items():
            if d["role"] == role and d["type"] in TYPE_GROUP:
                g[TYPE_GROUP[d["type"]]].append(c)
        return {k: v for k, v in g.items() if v}

    drop = [c for c, d in info.items() if d["type"] == "constant"]
    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        "# Auto-generated by scripts/classify_schema.py — REVIEW before use.",
        "# Vocab + numeric bins fit on data/processed/train.parquet ONLY (decision DL-008).",
        "schema: esma_annex2",
        f"id_col: {args.id_col}",
        f"time_col: {args.time_col}        # observation cutoff -> temporal coordinate",
        "num_buckets: 16",
        "zero_bucket: true",
        "",
        "drop:        # constant / no-signal columns",
    ]
    lines += [f"  - {c}" for c in drop]
    for role, key in (("static", "profile"), ("dynamic", "event")):
        lines.append(f"\n{key}:        # {role} fields")
        for sub, cols in group(role).items():
            lines.append(f"  {sub}:")
            lines += [f"    - {c}" for c in cols]
    lines += ["", "temporal:", "  reference: origination", "  log_seconds: true",
              "  cyclical: [month, quarter]", ""]
    Path(args.out).write_text("\n".join(lines))
    print(f"\nWrote draft: {args.out}")


if __name__ == "__main__":
    main()
